export default [
  { passion: "Harry Potter", active: false },
  { passion: "90s Kid", active: false },
  { passion: "SoundCloud", active: false },
  { passion: "Spa", active: false },
  { passion: "Self Care", active: false },
  { passion: "Heavy Metal", active: false },
  { passion: "House Parties", active: false },
  { passion: "Gymnastics", active: false },
  { passion: "Marvel", active: false },
  { passion: "Social Media", active: false },
  { passion: "Reading", active: false },
  { passion: "Country Music", active: false },
  { passion: "Hot Yoga", active: false },
  { passion: "Meditation", active: false },
  { passion: "Spotify", active: false },
  { passion: "Theater", active: false },
  { passion: "Home Workout", active: false },
  { passion: "Sneakers", active: false },
  { passion: "Walking", active: false },
  { passion: "Running", active: false },
  { passion: "Travel", active: false },
  { passion: "Movies", active: false },
  { passion: "Gym", active: false },
  { passion: "Hip Hop", active: false },
  { passion: "Skateboarding", active: false },
  { passion: "Walking My Dog", active: false },
  { passion: "Foodies Tour", active: false },
  { passion: "Football", active: false },
  { passion: "Investing", active: false },
  { passion: "Tennis", active: false },
  { passion: "Ice Cream", active: false },
  { passion: "Playstation", active: false },
  { passion: "Motor Sports", active: false },
  { passion: "Content Creation", active: false },
  { passion: "E-Sports", active: false },
  { passion: "Bicycle Racing", active: false },
  { passion: "Song Writer", active: false },
  { passion: "Tatoos", active: false },
  { passion: "Painting", active: false },
  { passion: "Surfing", active: false },
  { passion: "Museum", active: false },
  { passion: "Politics", active: false },
  { passion: "Art", active: false },
  { passion: "Live Music", active: false },
  { passion: "Wrestling", active: false },
  { passion: "Writing", active: false },
  { passion: "Makeup", active: false },
  { passion: "Volleyball", active: false },
  { passion: "NFTs", active: false },
  { passion: "Hiking", active: false },
  { passion: "Baking", active: false },
  { passion: "concerts", active: false },
  { passion: "clubbing", active: false },
  { passion: "Acapela", active: false },
  { passion: "Boxing", active: false },
  { passion: "Bar Chiling", active: false },
  { passion: "Table Tennis", active: false },
  { passion: "Stock Exchange", active: false },
  { passion: "Horror Movies", active: false },
  { passion: "Yoga", active: false },
  { passion: "Cars", active: false },
  { passion: "Fashion", active: false },
  { passion: "Baking", active: false },
  { passion: "Camping", active: false },
  { passion: "Outdoors", active: false },
  { passion: "Comedy", active: false },
  { passion: "Netflix", active: false },
  { passion: "Music", active: false },
  { passion: "Art Galleries", active: false },
  { passion: "Gardening", active: false },
  { passion: "Cooking", active: false },
  { passion: "Painting", active: false },
  { passion: "Real Estates", active: false },
  { passion: "Enterpreneurship", active: false },
  { passion: "Car Racing", active: false },
  { passion: "Choir", active: false },
  { passion: "Singing", active: false },
  { passion: "Gospell", active: false },
  { passion: "Sports", active: false },
  { passion: "SkinCare", active: false },
];
